### ISSUE TITLE
'version `GLIBC_2.33' not found'  on ubuntu 20.04.6LTS

### ISSUE THREAD

**Issue by QUEAHREN** [CrossPaste/crosspaste-desktop#2100]
### How frequently does the bug occur?

-- select --

### Description

我使用以下指令进行安装
```
wget https://github.com/CrossPaste/crosspaste-desktop/releases/download/1.0.12.1077/crosspaste_1.0.12-1077_amd64.deb
sudo apt install ./crosspaste_1.0.12-1077_amd64.deb
```

安装完成后无法正常启动crosspaste

### Stacktrace & log output

```shell
❯ crosspaste
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
12:58:38.594 [main] INFO com.crosspaste.CrossPaste -- Starting CrossPaste
12:58:38.599 [main] INFO com.crosspaste.app.DesktopAppLaunch -- Application lock acquired.
12:58:39.895 [main] INFO com.crosspaste.realm.RealmManager -- RealmManager createRealm - /home/qhehren/.local/shard/.crosspaste/data/crosspaste.realm
12:58:40.089 [main] INFO com.crosspaste.signal.LinuxIdentityKeyStoreFactory -- No found identityKey encrypt file
12:58:40.090 [main] INFO com.crosspaste.signal.LinuxIdentityKeyStoreFactory -- Creating new identityKey
12:58:40.099 [main] ERROR com.crosspaste.CrossPaste -- cant start crosspaste
java.lang.UnsatisfiedLinkError: /usr/lib/crosspaste/lib/runtime/lib/libsignal_jni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/crosspaste/lib/runtime/lib/libsignal_jni.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1993)
	at org.signal.libsignal.internal.Native.loadLibrary(Native.java:71)
	at org.signal.libsignal.internal.Native.loadNativeCode(Native.java:78)
	at org.signal.libsignal.internal.Native.<clinit>(Native.java:85)
	at org.signal.libsignal.protocol.ecc.ECPrivateKey.generate(ECPrivateKey.java:18)
	at org.signal.libsignal.protocol.ecc.Curve.generateKeyPair(Curve.java:14)
	at org.signal.libsignal.protocol.IdentityKeyPair.generate(IdentityKeyPair.java:42)
	at com.crosspaste.signal.LinuxIdentityKeyStoreFactory.createIdentityKeyStore(IdentityKeyStore.kt:247)
	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$53(CrossPaste.kt:327)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
	at org.koin.core.scope.Scope.get(Scope.kt:215)
	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$62(CrossPaste.kt:880)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
	at org.koin.core.scope.Scope.get(Scope.kt:215)
	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$47(CrossPaste.kt:815)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
	at org.koin.core.scope.Scope.get(Scope.kt:215)
	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$43(CrossPaste.kt:795)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
	at org.koin.core.scope.Scope.get(Scope.kt:215)
	at com.crosspaste.CrossPaste$Companion.initInject(CrossPaste.kt:615)
	at com.crosspaste.CrossPaste$Companion.main(CrossPaste.kt:526)
	at com.crosspaste.CrossPaste.main(CrossPaste.kt)
```

### Can you reproduce the bug?

Always

### Version

1.0.12

### OS

ubuntu 20.04.6LTS

**Comment by guiyanakuang** [comment]
@QUEAHREN  Thank you reporting this issue.

<img width="1570" alt="image" src="https://github.com/user-attachments/assets/873a5a82-ba22-476a-898c-9d50b460a83d">
https://launchpad.net/glibc/+packages

Based on my research, Ubuntu 22.04 is already using GLIBC version 2.35 by default. Your situation seems a bit unusual.
You can use `strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_` to check.

For crosspaste, we rely on the signal encryption library, which requires a minimum of `GLIBC 2.33`. Although it's possible to independently compile signal to lower its dependency version, this would increase the project's maintenance costs. Moreover, 2.33 doesn't seem to be a particularly high requirement.

**Comment by QUEAHREN** [comment]
> @QUEAHREN Thank you reporting this issue.
> 
> <img alt="image" width="54.1328125" height="21" src="https://private-user-images.githubusercontent.com/4069905/378299677-873a5a82-ba22-476a-898c-9d50b460a83d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA5MzQsIm5iZiI6MTcyOTUwMDYzNCwicGF0aCI6Ii80MDY5OTA1LzM3ODI5OTY3Ny04NzNhNWE4Mi1iYTIyLTQ3NmEtODk4Yy05ZDUwYjQ2MGE4M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMDg1MDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ1NmI2MWVjMjliZGMxOGMzMThiODUxNzM1NzBkMWJjNTQ2MjNjZjMzMmNjMGQzNjUwZmZlNDVhNmYyMTE3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1R8rc95HHNRm43VpHSMxDCvVOb0BZiQqni0tojJnrvs"> https://launchpad.net/glibc/+packages
> Based on my research, Ubuntu 22.04 is already using GLIBC version 2.35 by default. Your situation seems a bit unusual. You can use `strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_` to check.
> 
> For crosspaste, we rely on the signal encryption library, which requires a minimum of `GLIBC 2.33`. Although it's possible to independently compile signal to lower its dependency version, this would increase the project's maintenance costs. Moreover, 2.33 doesn't seem to be a particularly high requirement.
不好意思，我的系统是 20.04，已经更新了标题。我尝试更新GLIBC显示2.31是我目前最新的版本，所以如果需要使用crosspaste，我只能更新到ubuntu22.04吗？

**Comment by guiyanakuang** [comment]
The official support end date for Ubuntu 20.04 LTS is April 2025, so it has not been included in the maintenance scope.

CrossPaste is a fully open-source project, so besides upgrading your system, another option is to modify the signal dependency version and compile the Linux version yourself.

https://github.com/CrossPaste/crosspaste-desktop/blob/fa05241d1d7712492a8c2e4361f1d4de641b6178/gradle/libs.versions.toml#L30

https://mvnrepository.com/artifact/org.signal/libsignal-client

**Comment by Zephyr-One** [comment]
> ### How frequently does the bug occur?
> -- select --
> 
> ### Description
> 我使用以下指令进行安装
> 
> ```
> wget https://github.com/CrossPaste/crosspaste-desktop/releases/download/1.0.12.1077/crosspaste_1.0.12-1077_amd64.deb
> sudo apt install ./crosspaste_1.0.12-1077_amd64.deb
> ```
> 
> 安装完成后无法正常启动crosspaste
> 
> ### Stacktrace & log output
> ```shell
> ❯ crosspaste
> SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
> 12:58:38.594 [main] INFO com.crosspaste.CrossPaste -- Starting CrossPaste
> 12:58:38.599 [main] INFO com.crosspaste.app.DesktopAppLaunch -- Application lock acquired.
> 12:58:39.895 [main] INFO com.crosspaste.realm.RealmManager -- RealmManager createRealm - /home/qhehren/.local/shard/.crosspaste/data/crosspaste.realm
> 12:58:40.089 [main] INFO com.crosspaste.signal.LinuxIdentityKeyStoreFactory -- No found identityKey encrypt file
> 12:58:40.090 [main] INFO com.crosspaste.signal.LinuxIdentityKeyStoreFactory -- Creating new identityKey
> 12:58:40.099 [main] ERROR com.crosspaste.CrossPaste -- cant start crosspaste
> java.lang.UnsatisfiedLinkError: /usr/lib/crosspaste/lib/runtime/lib/libsignal_jni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/crosspaste/lib/runtime/lib/libsignal_jni.so)
> 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
> 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
> 	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
> 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
> 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
> 	at java.base/java.lang.System.loadLibrary(System.java:1993)
> 	at org.signal.libsignal.internal.Native.loadLibrary(Native.java:71)
> 	at org.signal.libsignal.internal.Native.loadNativeCode(Native.java:78)
> 	at org.signal.libsignal.internal.Native.<clinit>(Native.java:85)
> 	at org.signal.libsignal.protocol.ecc.ECPrivateKey.generate(ECPrivateKey.java:18)
> 	at org.signal.libsignal.protocol.ecc.Curve.generateKeyPair(Curve.java:14)
> 	at org.signal.libsignal.protocol.IdentityKeyPair.generate(IdentityKeyPair.java:42)
> 	at com.crosspaste.signal.LinuxIdentityKeyStoreFactory.createIdentityKeyStore(IdentityKeyStore.kt:247)
> 	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$53(CrossPaste.kt:327)
> 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
> 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
> 	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
> 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
> 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
> 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
> 	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
> 	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
> 	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
> 	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
> 	at org.koin.core.scope.Scope.get(Scope.kt:215)
> 	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$62(CrossPaste.kt:880)
> 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
> 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
> 	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
> 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
> 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
> 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
> 	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
> 	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
> 	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
> 	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
> 	at org.koin.core.scope.Scope.get(Scope.kt:215)
> 	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$47(CrossPaste.kt:815)
> 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
> 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
> 	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
> 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
> 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
> 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
> 	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
> 	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
> 	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
> 	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
> 	at org.koin.core.scope.Scope.get(Scope.kt:215)
> 	at com.crosspaste.CrossPaste$Companion.initKoinApplication$lambda$109$lambda$43(CrossPaste.kt:795)
> 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
> 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
> 	at org.koin.core.instance.SingleInstanceFactory.get$lambda$0(SingleInstanceFactory.kt:55)
> 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
> 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
> 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
> 	at org.koin.core.scope.Scope.resolveFromRegistry(Scope.kt:321)
> 	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:311)
> 	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:273)
> 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
> 	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
> 	at org.koin.core.scope.Scope.get(Scope.kt:215)
> 	at com.crosspaste.CrossPaste$Companion.initInject(CrossPaste.kt:615)
> 	at com.crosspaste.CrossPaste$Companion.main(CrossPaste.kt:526)
> 	at com.crosspaste.CrossPaste.main(CrossPaste.kt)
> ```
> 
> ### Can you reproduce the bug?
> Always
> 
> ### Reproduction Steps
> _No response_
> 
> ### Version
> 1.0.12
> 
> ### OS
> ubuntu 20.04.6LTS

和你一样的问题，请问怎么解决的

**Comment by guiyanakuang** [comment]
I apologize but there is no direct solution to this issue at the moment, as the project's signal dependency requires a minimum of GLIBC 2.33.
The possible solutions are:

Upgrade your system. Note that directly upgrading GLIBC alone in Ubuntu 20.04 could be harmful, as it might cause compatibility issues with other software.
Modify the project's source code to lower the signal dependency version, and compile CrossPaste yourself
